language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$(yarn global bin):$PATH"
cache: yarn
install:
  - yarn global add codecov
  - yarn global add coveralls
  - yarn
script: yarn test-coverage && yarn e2e-test-coverage
